import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
const dataRoot=path.resolve("data"); const outputDir=path.resolve("work/workbooks-after-29141"); await fs.mkdir(outputDir,{recursive:true});
const scope=JSON.parse(await fs.readFile(path.join(dataRoot,"scope-44.json"),"utf8"));
const defs=[]; for(const f of await fs.readdir(path.join(dataRoot,"definitions"))){ if(!f.endsWith(".json")) continue; const d=JSON.parse(await fs.readFile(path.join(dataRoot,"definitions",f),"utf8")); if(scope.standards.includes(d.number)) defs.push(d); }
defs.sort((a,b)=>a.number.localeCompare(b.number,"zh-CN"));
const rows=[]; for(const d of defs) for(const p of d.products) for(const i of p.indicators) rows.push([d.number,d.title,p.name,i.name,i.unit,i.id]);
const wb=Workbook.create(); const info=wb.worksheets.add("合并说明"); const map=wb.worksheets.add("当前规则汇总"); const history=wb.worksheets.add("历史版本");
info.getRange("A1:B1").merge(); info.getRange("A1").values=[["统一标准规则确认表合并报告"]]; info.getRange("A3:B11").values=[
 ["主表文件","统一标准规则确认表.xlsx"],["当前范围","46项强制性能耗限额标准"],["当前指标行数",rows.length],["合并方式","按标准编号+指标ID保留每一条规则；不按产品/工序名称去重。"],["同名产品处理","允许产品/工序名称相同，但指标名称必须区分；例如同一产品可分别保留单位产品综合能耗和电耗。"],["GB 29141-2024","替代GB 29141-2012、GB 29437-2012、GB 29441-2012；表1共10类工业硫酸工序，另含SO₂提浓工序限值、稀硝酸和工业冰醋酸。"],["条件修正","发烟硫酸在对应原料基础限额上增加35 kgce/t；硫黄制酸3级按低温热回收条件分支。"],["历史版本","旧版规则单独存放并带历史提示；未完成确认的旧版草案不进入正式计算包。"],["核对结果","当前确认表与规则定义均为当前46项；产品/工序名称未包含“单位产品能耗/电耗”等指标后缀。"],
]; info.getRange("A1:B1").format={fill:"#17365D",font:{bold:true,color:"#FFFFFF",size:16},horizontalAlignment:"center"}; info.getRange("A3:B11").format={wrapText:true,verticalAlignment:"top",borders:{preset:"all",style:"thin",color:"#B4C6E7"}}; info.getRange("A3:A11").format={fill:"#D9EAF7",font:{bold:true,color:"#17365D"}}; info.getRange("A1:B11").format.rowHeight=24; info.getRange("A1:B1").format.rowHeight=32; info.getRange("A1:A20").format.columnWidth=22; info.getRange("B1:B20").format.columnWidth=100; info.showGridLines=false;
map.getRange("A1:F1").merge(); map.getRange("A1").values=[["当前46项规则行汇总"]]; map.getRange("A3:F3").values=[["标准编号","标准名称","产品/工序","指标名称","单位","指标ID"]]; map.getRange(`A4:F${3+rows.length}`).values=rows; map.getRange("A1:F1").format={fill:"#17365D",font:{bold:true,color:"#FFFFFF",size:16},horizontalAlignment:"center"}; map.getRange("A3:F3").format={fill:"#2F75B5",font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",wrapText:true,borders:{preset:"all",style:"thin",color:"#B4C6E7"}}; map.getRange(`A4:F${3+rows.length}`).format={wrapText:true,borders:{preset:"all",style:"thin",color:"#B4C6E7"}}; map.getRange("A1:F1").format.rowHeight=32; map.freezePanes.freezeRows(3); map.showGridLines=false; for(const [c,w] of Object.entries({A:20,B:42,C:34,D:26,E:16,F:48})) map.getRange(`${c}1:${c}${rows.length+5}`).format.columnWidth=w;
history.getRange("A1:D1").merge(); history.getRange("A1").values=[["历史标准与替代关系"]]; history.getRange("A3:D3").values=[["旧标准","替代标准","状态","说明"]]; history.getRange("A4:D6").values=[["GB 29141-2012","GB 29141-2024","历史版本","可保留历史评价；结果带替代提示。"],["GB 29437-2012","GB 29141-2024","待确认","旧版草案规则不进入当前正式包。"],["GB 29441-2012","GB 29141-2024","待确认","旧版草案规则不进入当前正式包。"]]; history.getRange("A1:D1").format={fill:"#17365D",font:{bold:true,color:"#FFFFFF",size:16},horizontalAlignment:"center"}; history.getRange("A3:D3").format={fill:"#2F75B5",font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",borders:{preset:"all",style:"thin",color:"#B4C6E7"}}; history.getRange("A4:D6").format={wrapText:true,borders:{preset:"all",style:"thin",color:"#B4C6E7"}}; history.showGridLines=false; for(const [c,w] of Object.entries({A:22,B:22,C:16,D:60})) history.getRange(`${c}1:${c}10`).format.columnWidth=w;
const out=await SpreadsheetFile.exportXlsx(wb); await out.save(path.join(outputDir,"统一规则合并报告.xlsx")); console.log(`rows=${rows.length}`);
