"""Single source of truth for the UEBench product version (ECQ-RS05).

``pyproject.toml`` ``[project] version`` is the **only** authoritative product
version.  Every other version-bearing artifact in the formal release chain is
either *generated* from it by this module or *read* from it at build time, so no
release step depends on a human keeping two numbers in sync.

Two entry points matter:

* ``python tools/release_version.py --generate`` rewrites the derived files.
* ``python tools/release_version.py --check`` fails with exit code 1 if any
  derived file has drifted from ``pyproject.toml``.

``tests/test_release_version_consistency.py`` runs the ``--check`` logic, and
``scripts/build_candidate.ps1`` refuses to build when it fails.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"

#: Files this module generates from the authoritative version.
VERSION_MODULE = Path("src/uebench/_version.py")
VERSION_INFO = Path("packaging/version_info.txt")
VERSION_ISS = Path("packaging/version.iss")

_SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def project_version(pyproject: Path | None = None) -> str:
    """Return the authoritative version from ``pyproject.toml``."""
    path = pyproject or PYPROJECT
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    try:
        version = data["project"]["version"]
    except KeyError as exc:  # pragma: no cover - guards a broken pyproject
        raise RuntimeError(f"{path} 缺少 [project] version") from exc
    if not isinstance(version, str) or not _SEMVER_RE.match(version):
        raise RuntimeError(f"{path} 的版本号不是 X.Y.Z 形式：{version!r}")
    return version


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """``"0.2.0"`` -> ``(0, 2, 0, 0)`` for Windows VS_FIXEDFILEINFO."""
    parts = [int(part) for part in version.split(".")]
    if len(parts) > 4:
        raise RuntimeError(f"版本号段数过多：{version}")
    return tuple((parts + [0, 0, 0, 0])[:4])  # type: ignore[return-value]


def artifact_names(version: str) -> dict[str, str]:
    """Canonical release artifact file names for ``version``."""
    return {
        "portable": f"UEBench-{version}-win-x64.zip",
        "installer": f"UEBench-Setup-{version}-x64.exe",
        "source": f"UEBench-source-{version}.zip",
        "standard_package": "initial-standard-package-published.uebench",
        "template": "GB29446选煤电力消耗限额导入模板.xlsx",
        "sha256sums": "SHA256SUMS.txt",
        "payload_manifest": "payload-manifest.json",
        "build_info": "release-build-info.json",
        "helper_ps1": "验收助手.ps1",
        "helper_cmd": "验收助手.cmd",
        "release_notes": f"安装与发布说明-{version}.md",
        "delivery_list": f"交付清单-{version}.md",
    }


def render_version_module(version: str) -> str:
    return (
        '"""Generated by tools/release_version.py - do not edit by hand.\n'
        "\n"
        "The authoritative product version lives in ``pyproject.toml``;\n"
        "``tools/release_version.py --check`` fails the release when this file\n"
        "drifts from it.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        f'__version__ = "{version}"\n'
    )


def render_version_info(version: str) -> str:
    """PyInstaller ``version=`` resource file (numeric tuples + strings)."""
    major, minor, patch, build = version_tuple(version)
    return (
        "VSVersionInfo(\n"
        "  ffi=FixedFileInfo(\n"
        f"    filevers=({major}, {minor}, {patch}, {build}),\n"
        f"    prodvers=({major}, {minor}, {patch}, {build}),\n"
        "    mask=0x3f,\n"
        "    flags=0x0,\n"
        "    OS=0x40004,\n"
        "    fileType=0x1,\n"
        "    subtype=0x0,\n"
        "    date=(0, 0)\n"
        "  ),\n"
        "  kids=[\n"
        "    StringFileInfo([\n"
        "      StringTable(\n"
        "        u'080404B0',\n"
        "        [\n"
        "          StringStruct(u'CompanyName', u'UEBench'),\n"
        "          StringStruct(u'FileDescription', u'单位产品能耗对标软件'),\n"
        f"          StringStruct(u'FileVersion', u'{version}'),\n"
        "          StringStruct(u'InternalName', u'UEBench'),\n"
        "          StringStruct(u'OriginalFilename', u'UEBench.exe'),\n"
        "          StringStruct(u'ProductName', u'单位产品能耗对标软件'),\n"
        f"          StringStruct(u'ProductVersion', u'{version}')\n"
        "        ]\n"
        "      )\n"
        "    ]),\n"
        "    VarFileInfo([VarStruct(u'Translation', [2052, 1200])])\n"
        "  ]\n"
        ")\n"
    )


def render_version_iss(version: str) -> str:
    """Inno Setup include generated from the authoritative version."""
    return (
        "; Generated by tools/release_version.py - do not edit by hand.\n"
        f'#define MyAppVersion "{version}"\n'
    )


def derived_files(version: str | None = None) -> dict[Path, str]:
    """Map of derived file path -> expected content for the authoritative version."""
    resolved = version or project_version()
    return {
        VERSION_MODULE: render_version_module(resolved),
        VERSION_INFO: render_version_info(resolved),
        VERSION_ISS: render_version_iss(resolved),
    }


def check(root: Path | None = None, version: str | None = None) -> list[str]:
    """Return a list of drift descriptions (empty means everything is in sync)."""
    base = root or ROOT
    resolved = version or project_version(base / "pyproject.toml")
    problems: list[str] = []
    for relative, expected in derived_files(resolved).items():
        path = base / relative
        if not path.exists():
            problems.append(f"缺少生成文件：{relative}（应为 {resolved}）")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            problems.append(
                f"{relative} 与 pyproject.toml 的版本 {resolved} 不一致；"
                "请运行 python tools/release_version.py --generate"
            )
    return problems


def generate(root: Path | None = None, version: str | None = None) -> list[Path]:
    base = root or ROOT
    resolved = version or project_version(base / "pyproject.toml")
    written: list[Path] = []
    for relative, content in derived_files(resolved).items():
        path = base / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="UEBench 产品版本单一来源工具")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--print", action="store_true", help="打印权威版本号")
    group.add_argument("--generate", action="store_true", help="按权威版本重写派生文件")
    group.add_argument("--check", action="store_true", help="校验派生文件是否与权威版本一致")
    group.add_argument("--names", action="store_true", help="输出正式产物文件名（JSON）")
    parser.add_argument("--root", type=Path, default=None, help="仓库根目录（默认自动定位）")
    args = parser.parse_args(argv)

    base = args.root or ROOT
    version = project_version(base / "pyproject.toml")

    if args.generate:
        for path in generate(base, version):
            print(f"wrote {path}")
        return 0
    if args.check:
        problems = check(base, version)
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            print("版本一致性校验失败。", file=sys.stderr)
            return 1
        print(f"版本一致性校验通过：{version}")
        return 0
    if args.names:
        print(json.dumps(artifact_names(version), ensure_ascii=False))
        return 0
    print(version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
